#ifndef FINGERPRINTING_POC_HTTP_HEADER_ORDERING_H
#define FINGERPRINTING_POC_HTTP_HEADER_ORDERING_H

int http_header_ordering(char *hostname, CURL *curl);

#endif //FINGERPRINTING_POC_HTTP_HEADER_ORDERING_H
